### ISSUE TITLE
Add ability to unpack directly to USB mounted Vita

### ISSUE THREAD

**Issue by andrewmiskell** [jhonhenry10/NPS_Browser#12]
Would it be possible to unpack the pkg directly to a USB mounted Vita?

For example, I can specify a temporary directory on my HDD/SSD to download the pkg files to but then have NPS Browser extract the pkg files directly to the Vita via USB (eliminating the need to manually copy everything to the Vita after extraction and without having to store the pkg file on the Vita's SD card).

**Comment by ACiDxCHRiST** [comment]
You can already do that with the "Your pkg dec params" field in the options.
If your Vita shows up in windows as F Drive, just use this for your params:
{pkgFile} --make-dirs=ux --license="{zRifKey}" --queue-length=500 E:\

**Comment by jhonhenry10** [comment]
as ACiDxCHRiST said, there will be no build in functionality for this for now. use your command line parameter

**Comment by andrewmiskell** [comment]
Yeah, understood. I probably should have checked the command parameters for pkg_dec first.
