### ISSUE TITLE
PSP and PSX Games

### ISSUE THREAD

**Issue by MrCampy** [jhonhenry10/NPS_Browser#2]
There are some apps which can download PSP and PSX Games. If you can obtain the links and that your app convert them in CSO or ISO for use in Adrenaline, your app would be more complete. It is only a proposal

**Comment by TheRadziu** [comment]
Wrong repo to suggest that. It's NPS BROWSER app, It does not decrypt and/or do anything with downloaded pkg files on its own.

**Comment by jhonhenry10** [comment]
As TheRadziu said. There is no plan to add other sources to app others than your personal tsv files with your personals backups
