### ISSUE TITLE
Add game sizes

### ISSUE THREAD

**Issue by kenshin088** [jhonhenry10/NPS_Browser#21]

**Comment by TheRadziu** [comment]
https://i.imgur.com/kUlHthp.png 
Such information is already provided under Title cover on the right.

**Comment by kenshin088** [comment]
Oh sorry, I totally missed that. I was looking for it in a tab. I guess that would be redundant but also, I think it would be useful to have it in one of the tabs so you can sort by games you can download if you only have a limited amount of space left. I do this in pkgi. I look for smaller games to fill up my memory card and skip the ones I know i dont have room for. just a thought.

**Comment by jhonhenry10** [comment]
for now, it's not possible since size is known only when you click on a single item. There is no size information in the database.
