### ISSUE TITLE
Full pause/resume support

### ISSUE THREAD

**Issue by TheRadziu** [jhonhenry10/NPS_Browser#23]
As for now we can pause and resume downloads, but if the app is closed/restarted it doesn't know that there is already half-finished file and queue is empty. If the same game is added to the queue again, it starts to download the file again from zero.

My suggestion is to add better pause/resume support which will allow us to continue downloading after app is restarted. Something similar to what download managers and torrent clients do.

**Comment by IcySon55** [comment]
This would take a bit of work to do properly and I personally don't really see the need for pause at all. but maybe that's just me with my fast internet.

**Comment by prototye76** [comment]
we have slow connection like me 
for me it took me about 2 hours to download 1GB.
so this will be great in case if connection is lost or pc is shutdown.

**Comment by Reapfield** [comment]
not all countries have fast internet so a pause and resume support would be sufficient but upon my discovery, when i restarted the app and try to redownload the game (as i thought it would start from zero again) the app recognizes the file and continue where it left off

**Comment by jhonhenry10** [comment]
implemented in 0.76
