### ISSUE TITLE
App Window

### ISSUE THREAD

**Issue by ShinRaikdou** [jhonhenry10/NPS_Browser#30]
After 0.63a version and new GUI - I has problem with displaying info+picture about game.

Before
https://i.imgur.com/eXSOipi.png
After
https://i.imgur.com/Y3Dxpcy.png

Resizing didn't help. 
I am using Win7 without Aero ui. Turning it on is fixing this, but I can't use it for reasons...

**Comment by jhonhenry10** [comment]
really strange. I will look on this.

**Comment by jhonhenry10** [comment]
The problem is with your higher dpi than default. 
its really pain in the ass. If you can set dpi to default 100% it should work.
I will try find standard solution for this.

**Comment by jhonhenry10** [comment]
@IcySon55 can you help with this? I see you can better in this whole ui stuff ;)

**Comment by ShinRaikdou** [comment]
> If you can set dpi to default 100% it should work.

Well, this is not a solution for people with weak eyes or those who using PC on far distance(on TV for example). Hope you'll find standard solution.

**Comment by IcySon55** [comment]
I didn't know that Win7 dpi settings don't play nice with split panels because they work just fine on Windows 10 in other apps I've written.

I can think of a fix though, it will need some new registry keys to store the saved splitter positions and I'll have to allow moving the splitters.

**Comment by jhonhenry10** [comment]
Windows 10 aproach to DPI scale is different than in win7. In google i found program that set dpi in win10 as it doeas in win7, and i can repro the issue then.

here it is http://windows10_dpi_blurry_fix.xpexplorer.com/

**Comment by jhonhenry10** [comment]
After your changes it looks like this (resizing didnt fix text issue)
![nps_browser_2017-11-06_09-42-42](https://user-images.githubusercontent.com/32809866/32432208-fa93fe9a-c2d6-11e7-9fb9-72d44cb7db10.png)

**Comment by jhonhenry10** [comment]
I found possible solution:
Ive set main form AutoScaleMode to None. And it looks correct on higher dpi
