### ISSUE TITLE
NPS Browser passes "NOT REQUIRED" as zRIF

### ISSUE THREAD

**Issue by TheRadziu** [jhonhenry10/NPS_Browser#33]
as in title, if game has "NOT REQUIRED" as zRIF, NPS browser instead of ignoring this value, it does pass it to pkg2zip which errors out because of "zRIF too short".

Extraction works fine if {zRifKey} param is removed which confirm this as an issue.

**Comment by jhonhenry10** [comment]
fixed in next update
