### ISSUE TITLE
Re-downloading issue

### ISSUE THREAD

**Issue by u4113057** [jhonhenry10/NPS_Browser#35]
![temp_npsbrowser](https://user-images.githubusercontent.com/33534198/32639431-80d0add8-c5f6-11e7-8b17-7444bc93a79a.jpg)

when i try to re-download all the download file when program detect that its already had the pkg file locally it will pause and try next file (which is reasonable). but some of the downloaded file the program try to re-download and pending the pkg file to exceed original size. when pkg_dec the output will be larger than ti should be. all the file in output is the same as the smaller size one but only file app\PCSE00xxx\sce_sys\package\tail.bin is significantly larger than the other one.

**Comment by jhonhenry10** [comment]
fixed in 0.76
