### ISSUE TITLE
Contents not shown

### ISSUE THREAD

**Issue by azumukupoe** [jhonhenry10/NPS_Browser#36]
[ALL](https://i.imgur.com/JIzoWID.png)
[JP PSM](https://i.imgur.com/NERxtey.png)
[JP PSX](https://i.imgur.com/566AAaD.png)

**Comment by jhonhenry10** [comment]
probably you didn't add psm source in config

**Comment by azumukupoe** [comment]
don't you see the weird number of games?
there's more

**Comment by jhonhenry10** [comment]
what region settings do you have? i see there are wierd folder separators?

**Comment by azumukupoe** [comment]
@jhonhenry10
as shown
https://github.com/jhonhenry10/NPS_Browser/issues/36

**Comment by TheRadziu** [comment]
@azumukupoe he meant system region(windows), not game regions ^^

**Comment by azumukupoe** [comment]
Japan?

**Comment by Makein** [comment]
Press reload...

**Comment by azumukupoe** [comment]
It still doesn't show all games. 
I've already deleted settings. Is it my PC with i7 that's causing the problem?
I am confused.

**Comment by azumukupoe** [comment]
Please check my [settings](https://www.mediafire.com/file/avyk4ozuv957t84/NPS_Browser_0.77.npsSettings).
