### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by plato79** [jhonhenry10/NPS_Browser#37]
If I convert the http links to https, it doesn't see the games at all. Is there a check for this? I should be able to download via https instead of http I think.

**Comment by plato79** [comment]
I think I found the problem in RuForm.cs..
On line 225 it's like this:

`                            if ((!itm.zRif.ToLower().Contains("missing")) && itm.pkg.ToLower().Contains("http://"))`

I think it should be like this:

`                            if ((!itm.zRif.ToLower().Contains("missing")) && 
(itm.pkg.ToLower().Contains("http://") || itm.pkg.ToLower().Contains("https://")))`

**Comment by jhonhenry10** [comment]
good point, I will fix it.

**Comment by jhonhenry10** [comment]
fixed in next update
