### ISSUE TITLE
add PSP GAMES sheet support

### ISSUE THREAD

**Issue by TheRadziu** [jhonhenry10/NPS_Browser#39]
:)

**Comment by Makein** [comment]
:D
Well ISO, CSO extraction is fine.
But I prefer pkg->Eboot.bin with license installation

**Comment by TheRadziu** [comment]
? How it is related to this 'issue' ? 
pkg2zip now supports PSP games and PSP games sheet is ready, now only NPS browser lacks support for it.

**Comment by Makein** [comment]
How pkg2zip related to this 'issue' ?
You can use any extractor, so if your PSP GAMES sheet support related to this 'issue' .
Then other tools related too.
Because npsb use them

**Comment by juliosueiras** [comment]
I am pretty sure NPS Browser don't have option for psp / psp dlc right now

**Comment by jhonhenry10** [comment]
supported ;)
