### ISSUE TITLE
Not working with URLs

### ISSUE THREAD

**Issue by p0ngbr** [jhonhenry10/NPS_Browser#40]
Since I switched .TSV files to links, NPS doesn't work.

![image](https://user-images.githubusercontent.com/3867442/32992373-f3fcc508-cd30-11e7-8015-3f573f171431.png)

**Comment by TheRadziu** [comment]
can you access those links via web browser?

**Comment by p0ngbr** [comment]
Yep

**Comment by p0ngbr** [comment]
Now working in 0.75
