### ISSUE TITLE
Add label for games already downloaded

### ISSUE THREAD

**Issue by abduct** [jhonhenry10/NPS_Browser#41]
Add a label which can be used to sort titles that are already downloaded into the unpack directory.

This can be achieved by parsing the app directory for title IDs and then flagging the same IDs from the provided databases. Alternatively use a sqlite database saved locally on disk to keep track of such data for instances where users actively remove games after transferring them.

**Comment by jhonhenry10** [comment]
somehow implemented in 0.76
