### ISSUE TITLE
Allow .iso for PSP games

### ISSUE THREAD

**Issue by pordeciralgo** [jhonhenry10/NPS_Browser#43]
PSP games are unpacked in .cso format. It reduces size while working great for most games on (my) PSVita... but most of them freeze on (my) PSTV. I've checked and .iso games seem to work OK on (my) PSTV. Is it possible to choose from menu if we want either .cso or .iso?

**Comment by TheRadziu** [comment]
remove -c9 from pkg dec params
no -cX = iso 
-c[1-9] = cso where 1-9 is compression level.

**Comment by pordeciralgo** [comment]
Thank you @TheRadziu !!
