### ISSUE TITLE
[NPS Browser 0.75] Duplicated entry

### ISSUE THREAD

**Issue by p0ngbr** [jhonhenry10/NPS_Browser#44]
There are 3 entries from Tekken 6 in PSP_GAMES.tsv file:
```
NPUH10047	US	PSP	Tekken 6	http://zeus.dl.playstation.net/cdn/UP0700/NPUH10047_00/yJ8brnWN8VOCjTouwgXalIBC2qLpi4wifA69B49Yf44jRIS6kNVncUTujnUYFiP8maHKacw2AW3c0fUhqTjNI6B5Yn40x7xUXqsFn.pkg	UP0700-NPUH10047_00-NBGATEKKEN6PSPGO	2017-10-30 15:53:52
NPJH50184	JP	PSP	Tekken 6	http://zeus.dl.playstation.net/cdn/JP0700/NPJH50184_00/PhgGPXfduI0UxF7MPpmtlF0auO8wCMmNmc0TwCsEo23v25Hh2kVWHgjUkukRVQocKxXE8m11JP1KxGyt0HRwHdHMojpc6YjWKkCnE.pkg	JP0700-NPJH50184_00-0000000000000000	2017-10-30 15:53:52
ULES01376	EU	PSP	Tekken 6	http://zeus.dl.playstation.net/cdn/EP0700/ULES01376_00/6x1f31xP1Ui5pcR13HGqN8GvwLk84cn6O6DqmJ6HUtXiayGhnkW4UNQtr9qUQ2dlYhfVxH7ErF0oCRva8FI1lEN8ECifuiG0L35c5.pkg	EP0700-ULES01376_00-GPCTEKKEN6000001	2017-10-30 15:53:52
```
See pic

![image](https://user-images.githubusercontent.com/3867442/33056815-d4de1e94-ce6e-11e7-8301-544a0d66dc69.png)

I'm using https://nopaystation.com/ links

**Comment by jhonhenry10** [comment]
wierd - for me its working ok

can you confirm it was not "one time bug"? 
and show me screenshot from your config?

**Comment by p0ngbr** [comment]
Yes. It's a "one time bug". Now worked perfectly

thanks for quick reply :D

![image](https://user-images.githubusercontent.com/3867442/33081210-e673d930-cec0-11e7-89f7-3a249474c7ae.png)
