### ISSUE TITLE
[NPS Browser 0.76] File size wrong

### ISSUE THREAD

**Issue by p0ngbr** [jhonhenry10/NPS_Browser#48]
I'm trying to download some PSP games but I'm facing problems.

1. **Need for Speed: Shift** download came with corrupted pkg. (NPS Browser says _PKG decrypt err!_)

2. File size is _a little bit_ different (see pic)
![image](https://user-images.githubusercontent.com/3867442/33154193-d710df84-cfcd-11e7-8f6d-3da4aeb7adaa.png)

If I close and open **NPS Browser** again, the file size increases even more!
![image](https://user-images.githubusercontent.com/3867442/33154328-c5b5368a-cfce-11e7-8bf0-3af44d460b42.png)

![image](https://user-images.githubusercontent.com/3867442/33154379-2613fce6-cfcf-11e7-926d-bf18572d3c3e.png)

![image](https://user-images.githubusercontent.com/3867442/33154440-6877a8a8-cfcf-11e7-9a30-e79d6320f37d.png)

**Comment by jhonhenry10** [comment]
Ad1 - nfs shift is psp game, pkg_dec cant unpack it, use pkg2zip instead
ad2 - indeed there was an error. Fixed. thx
