### ISSUE TITLE
Couple of improvement/feature suggestions:

### ISSUE THREAD

**Issue by TheRadziu** [jhonhenry10/NPS_Browser#5]
I finally got some time to test this app and I have to say I'm quite surprised how nice it is, but I do have a couple of feature/improvement requests for you:

1. Switch for Queued / Simultaneous download mode,
~~2. Refresh Button and/or automatic refresh every X minutes if user is using URL,~~
3. PSM and UPDATES sheets support, 
~~4. Auto-Update feature,~~ Added it as Update notice I guess?
~~5. Automatic PKG file deletion after unpack, (ON/OFF switch)~~
6. An additional column in Games that will tell how many DLCs are currently available for that GameID,
7. Some support for batch selection (either ALL dlcs for a certain title, or by holding CTRL).

Cheers :)

**Comment by jhonhenry10** [comment]
Hi!
Ad1) there are only 2 simultaneously downloads, (unable to download more, servers blocking it)
Ad2) Done
Ad4) Done

**Comment by TheRadziu** [comment]
I'm happy with current 2) and 4) solutions, BUT I'd say to make an popup with repo's releases/latest link instead of simple window title change. Its too easy to miss right now.

Can you make a switch for ad 1) then? 1 or 2 simultaneous downloads.

**Comment by jhonhenry10** [comment]
Everything done except PSM and updates db, wont do this for now
