### ISSUE TITLE
Yet another batch of improvement requests

### ISSUE THREAD

**Issue by TheRadziu** [jhonhenry10/NPS_Browser#6]
~~1. Remove `AS` `TW` `KO/CN` regions, now they are merged with ASIA (PCSH and PCSD)~~ forgot about 'fixing' DLC tab as well. Now its okay
2. Ctrl + A support ~~for DLCs/GAME TAB~~ and Queue List on the bottom,
3. Add support for UPDATES and PSM tabs
4. When rightclicked on game with DLCs include "Download ALL Dlcs" which will add all available DLCs to Queue List.

:)

**Comment by TheRadziu** [comment]
New one: 
5. Add sorting by modification time (new row G), so people can check for recently added or updated stuff.

**Comment by jhonhenry10** [comment]
v0.56 
- add ctrl+a
- last modification date

**Comment by ACiDxCHRiST** [comment]
6. Make the cancel option respect/apply to all selected items in queue (right now if you select multiple items and then select "cancel", it only cancels 1 item) --- in fact make all right click options respect/apply to all selected items.

7. Add a minimize button to the titlebar

**Comment by jhonhenry10** [comment]
everything except Update support done in v0.60
updates wont be supported for now
