### ISSUE TITLE
grey out instead of deselecting a game when losing window focus

### ISSUE THREAD

**Issue by gatosardina** [jhonhenry10/NPS_Browser#61]
currently if you select a game in the list and lose focus of the browser window (after clicking the renascene.com link for example) the selection is lost, instead of becoming "grey" 
its not a vital issue but a minor annoyance

**Comment by gatosardina** [comment]
nevermind selection isnt lost
anyways if you click on the list to recover focus (instead of the taskbar icon, alt tabbing, etc) the title the mouse was hovering will be selected
dont know if that can be fixed , but it's even less important

**Comment by gatosardina** [comment]
sorry but i knew i noticed the game selected in the list being deselected
if you select a game and then click the renascene link the gmae becomes deselected in the list

**Comment by jhonhenry10** [comment]
fixed
