### ISSUE TITLE
Toggle display of 3.61+ games

### ISSUE THREAD

**Issue by Padoca85** [jhonhenry10/NPS_Browser#69]
Please add an option to filter the display of 3.61+ games.
While its good to have them on the list for preservation purposes, its kinda frustrating to scroll to this growing list of games we cant play. So having an option to toggle the display of them would be nice.

**Comment by mnadareski** [comment]
Duplicate of ( #20 )

**Comment by Padoca85** [comment]
oh, sorry, gonna close it then
